language: csharp
mono: 4.6.1
sudo: false
cache:
  directories:
  - thirdparty/download
addons:
  apt:
    packages:
    - lua5.1
    - nsis
    - nsis-common
    - dpkg
    - markdown
    - zlib1g-dev
    - libbz2-dev
    - cmake
    - genisoimage
    - fakeroot
    - zsync
env:
  secure: C0+Hlfa0YGErxUuWV00Tj6p45otC/D3YwYFuLpi2mj1rDFn/4dgh5WRngjvdDBVbXJ3duaZ78jPHWm1jr7vn2jqj9yETsCIK9psWd38ep/FEBM0SDr6MUD89OuXk/YyvxJAE+UXF6bXg7giey09g/CwBigjMW7ynET3wNAWPHPs=
script:
- travis_retry make all-dependencies
- make all SDK="-sdk:4.5"
- make check
- make check-scripts
- make test
- make nunit
branches:
- bleed
before_deploy:
- export PATH=$PATH:$HOME/usr/bin
- DOTVERSION=$TRAVIS_COMMIT
- cd packaging
- mkdir build
- "./package-all.sh ${TRAVIS_COMMIT} ${PWD}/build/"
- tar czvf "${PWD}/build/thirdparty.tar.gz" ../thirdparty/download
deploy:
  provider: releases
  api_key:
    secure: ayANRS6hRBZqhxhYQrOvfRVgO+FrkxZt6e6mo1GOD4NSRmH1uF3wRM9q9gIQbnMo8yiF7ibikBoDTQ92i78PUcavqEb6/7FUh3Vqqm6cpkjkxY9PxEJ/6sKGs6mhcXoOtkq3KipbCtNrO9JhWLE2ZCRKOyscXj1WV6qCv2zhapYxrc0C9ZmtqCu4Vr0xGprNdIIdTQu5sqV+WSU93xRPohP8ln+GFHM8Yo5QI17y0ICRWqK2Zyt5t0htFXqgHRdD3XOTxwenK35UxXsNsIj/w4z1snGjTu5dklZT7YvbmgKFHUNMGznjxLfk0vEFdNlYWw8zJoGV/Ko/FSbFswhlBFMAvqWES0AJtNyr5IrOQcqClzJ2bBX0MhDE4qrHR1pC8jpLj8Kev5QLM2Y/0dNGbcmYK9bZ3wVsMTlBsgQoji4DfYtm0KHJTLzZgZt6V7bcXI+GJrhCyyPwK5b5PFgZKosdINyoADsxsla7BS8qye7Yjre5im+Xxf2RH4GfIWigV0YYfXUHWe4hSSO59BMxTyqaSqfBsdsxIDsuP9dY+rRi9X5G8gzuFu/P5QLe27j4k5fVueU5YgJ0m9lCkhcnIG5H4PNPaRDn4W4PFjz18UajFgKdpGFiMnx2Aq2ZC76DpzGO/lObUheDM8AiboXImFGLGNoPi/+5Flz3BGDDNAM=
  skip_cleanup: true
  file_glob: true
  file: build/*
  on:
    repo: fusion809/OpenRA
    branch: bleed
